#include <stdio.h>
#include <curl/curl.h>

#include "json_helpers.h"
#include "Python.h"

#define NUM_REGIONI 21
#define ENDPOINT "https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-regioni.json"
#define PATH "data.json"


const char* regioni[] = {
			"Lombardia", "Lazio", "Campania", "Sicilia", "Veneto",
           "Emilia Romagna", "Abbruzzo", "Basilicata", "P.A. Bolzano",
           "Calabria", "Friuli Venezia Giulia", "Liguria", "Marche", "Molise",
           "Piemonte", "Puglia", "Sardegna", "Toscana", "P.A. Trento", "Umbria",
           "Valle d'Aosta"
		   };

// in part autogenerated via curl --libcurl ...
int update_data() {
	CURLcode ret;
	CURL *hnd;
	FILE *data = fopen("data.json", "w");

	hnd = curl_easy_init();
	curl_easy_setopt(hnd, CURLOPT_BUFFERSIZE, 102400L);
	curl_easy_setopt(hnd, CURLOPT_URL, ENDPOINT);
	curl_easy_setopt(hnd, CURLOPT_USERAGENT, "curl/7.68.0");
	curl_easy_setopt(hnd, CURLOPT_WRITEDATA, data);

	ret = curl_easy_perform(hnd);

	curl_easy_cleanup(hnd);
	hnd = NULL;
	fclose(data);
	(int)ret;
}

int main() {
	update_data();
	char *data_str;
	totale_regione **tot_reg_arr;
	
	long data_f_size = load_json(&data_str, PATH);
	long reg_data_len = get_tot_reg_data(&tot_reg_arr, data_str, data_f_size);
	
	printf("%ld, %ld\n", data_f_size, reg_data_len);

	Py_Initialize();
	PyRun_SimpleString("import matplotlib.pyplot as plt");
	PyRun_SimpleString("import sys");
	for(int i = 0; i < NUM_REGIONI; i++) {
		PyObject *arr = PyList_New(0);
		for(long j = 0; j < reg_data_len; j++) {
			if(strcmp(tot_reg_arr[j]->regione, regioni[i]) == 0) {
				PyList_Append(arr, PyLong_FromUnsignedLong(tot_reg_arr[j]->tot_casi));
			}
		}
		PySys_SetObject("arr", arr);
		PySys_SetObject("regione", PyUnicode_FromString(regioni[i]));
		PyRun_SimpleString("plt.plot(sys.arr, label=sys.regione)");
	}
	PyRun_SimpleString("plt.grid(linestyle='-', linewidth=2)");
    PyRun_SimpleString("plt.legend()");
	PyRun_SimpleString("plt.savefig('graph.png')");
	Py_Finalize();
	Py_Exit(0);

	free_tot_reg(tot_reg_arr, reg_data_len);
	free(data_str);

	return 0;
}

